name: Run ColliderVM Toy Demo

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-toy:
    name: Run toy preset on ${{ matrix.os }} / ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust (${{ matrix.rust }})
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{ matrix.rust }}

      - name: Cache cargo registry + build
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --verbose

      - name: Run ColliderVM toy simulation
        run: cargo run --bin collidervm_toy -- --input 102 --preset medium
